Add dashboard rebuild to post install
swiftotter/homebrew-den pull request #2
Opened 2022-10-06 04:41 UTC by bap14

This adds some "required" items for Homebrew Formulae, as well as adds a post install hook that will rebuild the Den Dashboard image to use the current version.

This should be merged together with my other PR in swiftotter/den repo as there are necessary dockerfile and index.html updates that are needed for this to work.

2022-10-06 04:42 UTC, bap14 commented
Den PR: https://github.com/swiftotter/den/pull/89

2022-10-06 12:18 UTC, navarr requested changes

2022-10-06 12:18 UTC, navarr commented on Formula/den.rb.template
> +  conflicts_with "davidalger/warden/warden", because: "Den is a replacement fork of Warden"
I'm unfamiliar with Homebrew's `conflicts_with`.  Will this prevent installing one or the other?  There is no conflict if both are installed at the same time, though they certainly can't both have services running at the same time.

2022-10-06 12:18 UTC, navarr commented on Formula/den.rb.template
> +      This command will automatically run an installation if necessary to setup a trusted
I don't see anywhere in this file that `den install` is being ran?

2022-10-06 12:18 UTC, navarr commented on Formula/den.rb.template
> +      system "docker",
Does build also restart?  In my experience it does not.

2022-10-06 13:04 UTC, bap14 commented on Formula/den.rb.template
> +  conflicts_with "davidalger/warden/warden", because: "Den is a replacement fork of Warden"
@navarr I don't believe it will prevent it, just issue an error / warning if it's installed. I'll remove it.

2022-10-06 13:06 UTC, bap14 commented on Formula/den.rb.template
> +      This command will automatically run an installation if necessary to setup a trusted
I can revert this. It's an alternative way to say the same thing. Homebrew doesn't allow modifying anything outside of its sandbox, so running `den install` for the current user isn't possible unfortunately. I'll revert this.

2022-10-06 13:16 UTC, bap14 commented on Formula/den.rb.template
> +      system "docker",
I'll fix this by at least always starting the dashboard container.

2022-10-06 13:20 UTC, bap14 commented on Formula/den.rb.template
> +      system "docker",
There is now a command to restart the dashboard after build.

2022-10-06 13:23 UTC, navarr commented on Formula/den.rb.template
> +      den_version = "testing-bap14"
```suggestion
```

Leftover testing code

2022-10-06 13:23 UTC, bap14 commented on Formula/den.rb.template
> +      den_version = "testing-bap14"
Just removed it.

2022-10-06 13:47 UTC, bap14 commented on Formula/den.rb.template
> +  conflicts_with "davidalger/warden/warden", because: "Den is a replacement fork of Warden"
I removed this in a later commit.

2022-10-06 13:48 UTC, bap14 commented on Formula/den.rb.template
> +      This command will automatically run an installation if necessary to setup a trusted
I've reverted this text to the original style.

2022-10-06 15:25 UTC, bap14 commented
@navarr I've resolved all your comments.

2022-10-06 20:37 UTC, merged

2022-10-17 08:05 UTC, ihor-sviziev commented
@bap14 @navarr,
today I tried to run `brew upgrade` while my Docker Desktop wasn't running yet (pretty OK situation if you're on MacOS). 
And it failed to update den.
<img width="967" alt="image" src="https://user-images.githubusercontent.com/1873745/196122060-c85eb97a-6bbc-4b51-93a0-f6c836af4b75.png">
Maybe we should move this logic to https://github.com/swiftotter/den/blob/main/commands/install.cmd#L2 ?